# Usa uma imagem leve do Python
FROM python:3.9

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas as dependências primeiro (melhora o cache do Docker)
COPY requirements.txt ./ 

# Instala as dependências do Locust e do Prometheus Client
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip && \
rm -rf /var/lib/apt/lists/*

CMD ["python3", "script.py"]